# Generated by Django 5.1.1 on 2024-09-30 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.clinic'),
        ),
    ]
